### ISSUE TITLE
Convert Consititution to markdown

### ISSUE THREAD

**Issue by klumb** [UNO-Mozilla-Campus-Club/Start-Here#15]
https://github.com/UNO-Mozilla-Club/UNO-Mozilla-Club/blob/master/governance/Consitution_UNO_Mozilla_Club.docx

**Comment by Nebrethar** [comment]
I finished with the conversion to markdown and PR is open. It may need some work but that is explained in the PR.

**Comment by Nebrethar** [comment]
Whoops. #20
